sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/config/routes.rb
Rails.application.routes.draw do
  resources :products
  get "static_pages/home" 
  get "static_pages/help"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/models/product.rb
class Product < ApplicationRecord
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # app/controllers/application_controller.rb
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i(show edit update destroy)

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html do
          redirect_to product_url(@product),
                      notice: "Product was successfully created."
        end
        format.json{render :show, status: :created, location: @product}
      else
        format.html{render :new, status: :unprocessable_entity}
        format.json do
          render json: @product.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html do
          redirect_to product_url(@product),
                      notice: "Product was successfully updated."
        end
        format.json{render :show, status: :ok, location: @product}
      else
        format.html{render :edit, status: :unprocessable_entity}
        format.json do
          render json: @product.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html do
        redirect_to products_url,
                    notice: "Product was successfully destroyed."
      end
      format.json{head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name)
  end
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t("title")
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container d-flex flex-center">
        <%= link_to t("sample_app"), "#", id: "logo" %>
        <div>
          <%= link_to t("english"), locale:"en" %> |
          <%= link_to t("vietnamese"), locale:"vi" %>
        </div>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to t("home"), static_pages_home_path %></li>
            <li><%= link_to t("help"), static_pages_help_path %></li>
            <li><%= link_to t("login"), "#" %></li>
          </ul>
        </nav>
      </div>
</header>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= link_to t("show"), product %></td>
  <td><%= link_to t("edit"), edit_product_path(product) %></td>
  <td><%= link_to t("destroy"), product, method: :delete, data: { confirm: "Are you sure ?" } %></td>
</tr>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= t("product") %></h1>
<button class="btn btn-success"><%= link_to t("new_product"), new_product_path %></button>
<div id="products">
  <table>
    <thead>
      <tr>
        <th><%= t("name") %></th>
        <th colspan=3></th>
      </tr>
      <tbody>
          <%# <%= render partial: "product", collection: @products %>
          <%= render (@products) || "No Products" %>
      </tbody>
    </thead>
  </table>
</div>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/static_pages/help.html.erb
<% provide :title, t("help")%>
<h1>StaticPages#help</h1>
Hello
<p>Find me in app/views/static_pages/help.html.erb</p>

sample_app-chapter_3_4_5/sample_app-chapter_3_4_5/app/views/static_pages/home.html.erb
<% provide :title, t("home")%>
<h1>StaticPages#home</h1>
This is Home Page
<p>Find me in app/views/static_pages/home.html.erb</p>
<%= link_to "Rails Tutorials Get Start", "https://guides.rubyonrails.org/getting_started.html" %>